languageCode = 'en-sg'
title = 'PocketPal'
theme = 'ace-documentation'
disablePathToLower = true

[[menu.shortcuts]]
name = "Home"
url = "/"
weight = 10

[[menu.shortcuts]]
name = "<i class='fab fa-github'></i>"
url = "https://github.com/AY2223S2-CS2113-W15-2/tp"
weight = 10
